using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyCookBookApp.Models;
using MyCookBookApp.Services;
using System.Collections.Generic;

namespace MyCookBookApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRecipeService _recipeService;

        public HomeController(ILogger<HomeController> logger, IRecipeService recipeService)
        {
            _logger = logger;
            _recipeService = recipeService;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Home";
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Recipes()
        {
            return View();
        }

        public IActionResult addRecipe()
        {
            return View();
        }

        // action method to handle dynamic recipe IDs
        [Route("recipes/{id}")]
        public IActionResult RecipeDetail(string id)
        {
            // Fetch the recipe details based on the ID
            ViewData["RecipeId"] = id;
            return View("RecipeDetails");
        }

        [HttpPost]
        public async Task<IActionResult> AddRecipe(string Name, string Category, string Instructions, string Thumbnail, List<string> IngredientNames, List<string> IngredientQuantities)
        {
            var ingredients = new Dictionary<string, string>();
            for (int i = 0; i < IngredientNames.Count; i++)
            {
                ingredients[IngredientNames[i]] = IngredientQuantities[i];
            }

            var newRecipe = new Recipe
            {
                // Id will be generated by the API
                Name = Name,
                Category = Category,
                Instructions = Instructions,
                Thumbnail = Thumbnail,
                Ingredients = ingredients
            };

            var addedRecipe = await _recipeService.AddRecipeAsync(newRecipe);
            Console.WriteLine("Added recipe: {0}", addedRecipe.Id);
            return RedirectToAction("Recipes");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}